#!/bin/sh
# Script to re-start the LRR process.

# Process passed-in platform environment
# variables such as LRR_ROOT (if needed).
ROOTACT=$LRR_ROOT
export ROOTACT

if [ -f ${ROOTACT}/lrr/com/_parameters.sh ]
then                  
    . ${ROOTACT}/lrr/com/_parameters.sh 2>&1 >/dev/null
fi

# For example:
# optional output
# echo "Re-started"
# Must return status code 0 if successful
# exit 0

$SERVICELRR restart
status=$?

exit $status

